/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as ApiIndexRouteImport } from './routes/api.index'
import { Route as ColonyIndexRouteImport } from './routes/colony.index'
import { Route as ColonySlugRouteImport } from './routes/colony.$slug'
import { Route as ResidentsIndexRouteImport } from './routes/residents.index'
import { Route as ResidentsIdRouteImport } from './routes/residents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonyIndexRoute = ColonyIndexRouteImport.update({
  id: '/colony/',
  path: '/colony/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColonySlugRoute = ColonySlugRouteImport.update({
  id: '/colony/$slug',
  path: '/colony/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsIndexRoute = ResidentsIndexRouteImport.update({
  id: '/residents/',
  path: '/residents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsIdRoute = ResidentsIdRouteImport.update({
  id: '/residents/$id',
  path: '/residents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/buy': typeof BuyRoute
  '/join': typeof JoinRoute
  '/projects': typeof ProjectsRoute
  '/signal': typeof SignalRoute
  '/colony/$slug': typeof ColonySlugRoute
  '/residents/$id': typeof ResidentsIdRoute
  '/api/': typeof ApiIndexRoute
  '/colony/': typeof ColonyIndexRoute
  '/residents/': typeof ResidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/buy': typeof BuyRoute
  '/join': typeof JoinRoute
  '/projects': typeof ProjectsRoute
  '/signal': typeof SignalRoute
  '/colony/$slug': typeof ColonySlugRoute
  '/residents/$id': typeof ResidentsIdRoute
  '/api': typeof ApiIndexRoute
  '/colony': typeof ColonyIndexRoute
  '/residents': typeof ResidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/buy': typeof BuyRoute
  '/join': typeof JoinRoute
  '/projects': typeof ProjectsRoute
  '/signal': typeof SignalRoute
  '/colony/$slug': typeof ColonySlugRoute
  '/residents/$id': typeof ResidentsIdRoute
  '/api/': typeof ApiIndexRoute
  '/colony/': typeof ColonyIndexRoute
  '/residents/': typeof ResidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board'
    | '/buy'
    | '/join'
    | '/projects'
    | '/signal'
    | '/colony/$slug'
    | '/residents/$id'
    | '/api/'
    | '/colony/'
    | '/residents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board'
    | '/buy'
    | '/join'
    | '/projects'
    | '/signal'
    | '/colony/$slug'
    | '/residents/$id'
    | '/api'
    | '/colony'
    | '/residents'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board'
    | '/buy'
    | '/join'
    | '/projects'
    | '/signal'
    | '/colony/$slug'
    | '/residents/$id'
    | '/api/'
    | '/colony/'
    | '/residents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardRoute: typeof BoardRoute
  BuyRoute: typeof BuyRoute
  JoinRoute: typeof JoinRoute
  ProjectsRoute: typeof ProjectsRoute
  SignalRoute: typeof SignalRoute
  ColonySlugRoute: typeof ColonySlugRoute
  ResidentsIdRoute: typeof ResidentsIdRoute
  ApiIndexRoute: typeof ApiIndexRoute
  ColonyIndexRoute: typeof ColonyIndexRoute
  ResidentsIndexRoute: typeof ResidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colony/': {
      id: '/colony/'
      path: '/colony'
      fullPath: '/colony/'
      preLoaderRoute: typeof ColonyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colony/$slug': {
      id: '/colony/$slug'
      path: '/colony/$slug'
      fullPath: '/colony/$slug'
      preLoaderRoute: typeof ColonySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/': {
      id: '/residents/'
      path: '/residents'
      fullPath: '/residents/'
      preLoaderRoute: typeof ResidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/$id': {
      id: '/residents/$id'
      path: '/residents/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof ResidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardRoute: BoardRoute,
  BuyRoute: BuyRoute,
  JoinRoute: JoinRoute,
  ProjectsRoute: ProjectsRoute,
  SignalRoute: SignalRoute,
  ColonySlugRoute: ColonySlugRoute,
  ResidentsIdRoute: ResidentsIdRoute,
  ApiIndexRoute: ApiIndexRoute,
  ColonyIndexRoute: ColonyIndexRoute,
  ResidentsIndexRoute: ResidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
